version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=n8n
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # CORRIGIDO: O usuário (-U) agora é 'default', o mesmo definido em POSTGRES_USER.
      test: ["CMD-SHELL", "pg_isready -U default -d n8n"]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=default
      - DB_POSTGRESDB_PASSWORD=12345
      - GENERIC_TIMEZONE=America/Sao_Paulo # Ajustado para um timezone mais comum no Brasil
      - TZ=America/Sao_Paulo
      # As variáveis abaixo são para uso em produção com domínio, podem ser comentadas para teste local
      # - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      # - N8N_PROTOCOL=https
      # - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
    ports:
      - "127.0.0.1:5678:5678"
    volumes:
      - ~/.n8n:/home/node/.n8n
    depends_on:
      - postgres

volumes:
  postgres_data: